import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import { ThemeProvider } from "@/components/theme-provider"
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/icons/logo";
import "./globals.css";
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, navigationMenuTriggerStyle } from "@/components/ui/navigation-menu";
import { CircleAlertIcon } from "lucide-react";


const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="fixed w-full z-50 bg-background border-b">
            <div className="container mx-auto h-16 flex justify-between">
              <div className="flex items-center gap-2">
                <Logo className="w-8 h-8" />
                <span className="font-bold tracking-tight text-xl uppercase">Octogone</span>
              </div>

              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem>
                    <NavigationMenuLink className={navigationMenuTriggerStyle()} render={<Link href="#about">À propos</Link>} />
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink className={navigationMenuTriggerStyle()} render={<Link href="#services">Services</Link>} />
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink className={navigationMenuTriggerStyle()} render={<Link href="#projects">Projets</Link>} />
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuLink className={navigationMenuTriggerStyle()} render={<Link href="#contact">Contact</Link>} />
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
            </div>
          </nav >

          {children}

          <footer className="py-6 border-t">
            <div className="container mx-auto px-6 flex flex-col md:flex-row justify-center items-center gap-4">
              <p className="text-xs">
                © 2025 Octogone 3D Prints™. Tous droits réservés.
              </p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
